name: revenge_platform
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

   # Base
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  hexcolor: ^2.0.3
  shared_preferences: ^2.0.5
  lottie: ^1.0.1
  # flutter_svg: ^0.22.0
  modal_bottom_sheet: ^2.0.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.3.3
  rxdart: ^0.27.3
  image_picker: ^0.8.4+10
  flutter_speed_dial: ^5.0.0
  syncfusion_flutter_datepicker: ^19.4.53
  flutter_feather_icons: ^2.0.0+1
  ant_icons: ^2.0.0-nullsafety.0
  ionicons: ^0.1.2
  eva_icons_flutter: ^3.0.2
  flutter_hooks: ^0.18.2+1
  better_player: ^0.0.81
  bot_toast: ^4.0.1
  connectivity_plus: ^2.2.0
  custom_text: ^0.6.0-dev.1
  dart_vlc: ^0.1.9
  hooks_riverpod: ^2.0.0-dev.0
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  lucide_icons: ^0.17.11
  libadwaita: ^1.2.0-dev
  libadwaita_bitsdojo: ^0.5.3
  libadwaita_searchbar_ac: ^0.5.3
  readmore: ^2.1.0
  timeago: ^3.2.1
  share_plus: ^3.0.4
  permission_handler: ^8.3.0
  youtube_explode_dart: ^1.11.0
  miniplayer: ^1.0.1
  email_validator: ^2.0.1
  string_validator: ^0.3.0
  line_icons:
  video_player: ^2.4.0
  chewie: ^1.3.2
  material_design_icons_flutter: ^5.0.6595
  flutter_slidable: ^1.2.0
  file_picker: ^4.1.6
  dotted_border: ^2.0.0+1
  im_stepper: ^0.1.3
  convex_bottom_bar: ^3.0.0
  just_audio: ^0.9.7
  record: ^3.0.0
  emoji_picker_flutter: ^1.1.2
  bubble: ^1.2.1
  open_file: ^3.2.1
  fl_toast: ^3.1.0
  page_transition: ^2.0.5
  pinch_zoom: ^1.0.0
  pfile_picker: ^3.1.4+2
  rflutter_alert: ^2.0.4
  fluttericon: ^2.0.0
  loading_overlay: ^0.3.0
  path_provider: ^2.0.9
  jitsi_meet: ^4.0.0
  status_view: ^0.0.2
  percent_indicator: ^3.0.1
  smooth_page_indicator: ^1.0.0+2


  # Login Auth
  logging: ^1.0.1

  #firebase
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_messaging: ^11.2.12
  firebase_storage: ^10.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/svg/
    - assets/lottie/
    - assets/audios/
    - assets/videos/

  fonts:
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
